import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// CSS
import "./globals.css";

// Images
import { Loader } from "lucide-react";

// Imports
import ServerProvider from "@/components/providers/server-provider";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-mono antialiased`}
      >
        <Suspense
          fallback={
            <main className="w-full h-screen custom-flex-center">
              <Loader size={32} className="animate-spin" />
            </main>
          }
        >
          <ServerProvider>{children}</ServerProvider>
        </Suspense>
      </body>
    </html>
  );
}
